// Copyright (c) 2016-2025 Knuth Project developers.
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <concepts>
#include <optional>

#include <test_helpers.hpp>

using namespace kth;
using namespace kd;
using namespace kth::domain::wallet;

// Start Test Suite: bitcoin uri tests

// operator!= is auto-generated by C++20 rewriting `a != b` to `!(a == b)`
// when only `operator==` is defined. Verified at compile time here so
// the invariant surfaces in the closest possible location to the type
// (and mirrors the C-API `_not_equal` binding synthesized by the
// generator).
static_assert(
    requires(bitcoin_uri const& a, bitcoin_uri const& b) {
        { a != b } -> std::same_as<bool>;
        { a == b } -> std::same_as<bool>;
    });

// Constructors
// ----------------------------------------------------------------------------

TEST_CASE("bitcoin uri default invalid", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri().valid());
}

TEST_CASE("bitcoin uri parse from bitcoin scheme valid", "[bitcoin uri]") {
    REQUIRE(bitcoin_uri::parse_from("bitcoin:"));
}

TEST_CASE("bitcoin uri parse from scheme mixed case normalized", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcOin:");
    REQUIRE(uri);
    REQUIRE(uri->encoded() == "bitcoin:");
}

TEST_CASE("bitcoin uri parse from invalid scheme error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("fedcoin:"));
}

TEST_CASE("bitcoin uri parse from payment address only error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD"));
}

TEST_CASE("bitcoin uri parse from stealth address only error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i"));
}

TEST_CASE("bitcoin uri parse from fragment error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("bitcoin:#satoshi"));
}

TEST_CASE("bitcoin uri parse from strict reject non ascii", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("bitcoin:?label=Some テスト"));
}

TEST_CASE("bitcoin uri parse from non strict accept non ascii", "[bitcoin uri]") {
    REQUIRE(bitcoin_uri::parse_from("bitcoin:?label=Some テスト", false));
}

// Setters
// ----------------------------------------------------------------------------

TEST_CASE("bitcoin uri set path payment address expected encoding", "[bitcoin uri]") {
    auto const expected_payment = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD";
    auto const expected_uri = std::string("bitcoin:") + expected_payment;

    bitcoin_uri uri;
    REQUIRE(uri.set_path(expected_payment));
    REQUIRE(uri.encoded() == expected_uri);
}

TEST_CASE("bitcoin uri set path stealth address expected encoding", "[bitcoin uri]") {
    auto const expected_payment = "hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i";
    auto const expected_uri = std::string("bitcoin:") + expected_payment;

    bitcoin_uri uri;
    REQUIRE(uri.set_path(expected_payment));
    REQUIRE(uri.encoded() == expected_uri);
}

TEST_CASE("bitcoin uri set path reset stealth after payment expected encoding", "[bitcoin uri]") {
    auto const expected_stealth = "hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i";
    auto const expected_uri = std::string("bitcoin:") + expected_stealth;

    bitcoin_uri uri;
    auto const payment = payment_address::parse_from("113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD").value();
    REQUIRE(payment.valid());
    uri.set_address(payment);
    auto const stealth = stealth_address::parse_from(expected_stealth);
    REQUIRE(stealth);
    uri.set_address(*stealth);
    REQUIRE(uri.encoded() == expected_uri);
}

TEST_CASE("bitcoin uri set path reset payment after stealth expected encoding", "[bitcoin uri]") {
    auto const expected_payment = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD";
    auto const expected_uri = std::string("bitcoin:") + expected_payment;

    bitcoin_uri uri;
    auto const stealth = stealth_address::parse_from("hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i");
    REQUIRE(stealth);
    uri.set_address(*stealth);
    uri.set_address(payment_address::parse_from(expected_payment).value());
    REQUIRE(uri.encoded() == expected_uri);
}

TEST_CASE("bitcoin uri set path reset path false", "[bitcoin uri]") {
    auto const expected_payment = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD";
    auto const expected_uri = std::string("bitcoin:") + expected_payment;

    bitcoin_uri uri;
    auto const stealth = stealth_address::parse_from("hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i");
    REQUIRE(stealth);
    uri.set_address(*stealth);

    // The set_path will not reset a path. This is necessary to catch failures in non-strict parsing.
    REQUIRE( ! uri.set_path(expected_payment));
}

TEST_CASE("bitcoin uri set amount reset amount latter amount", "[bitcoin uri]") {
    bitcoin_uri uri;
    uri.set_amount(10000000000);
    uri.set_amount(120000);
    REQUIRE(uri.encoded() == "bitcoin:?amount=0.0012");
}

TEST_CASE("bitcoin uri all setters complex uri expected encoding", "[bitcoin uri]") {
    bitcoin_uri uri;
    uri.set_path("113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD");
    uri.set_amount(120000);
    uri.set_label("&=\n");
    uri.set_message("hello bitcoin");
    uri.set_r("http://example.com?purchase=shoes&user=bob");

    REQUIRE(uri.encoded() ==
                "bitcoin:113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD?"
                "amount=0.0012&"
                "label=%26%3D%0A&"
                "message=hello%20bitcoin&"
                "r=http://example.com?purchase%3Dshoes%26user%3Dbob");
}

TEST_CASE("bitcoin uri set parameter amount denormalized normalized", "[bitcoin uri]") {
    bitcoin_uri uri;
    REQUIRE(uri.set_parameter("amount", ".0012"));
    REQUIRE(uri.encoded() == "bitcoin:?amount=0.0012");
}

// Getters
// ----------------------------------------------------------------------------

TEST_CASE("bitcoin uri amount set expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?amount=0.0012");
    REQUIRE(uri);
    REQUIRE(uri->amount() == 120000u);
}

TEST_CASE("bitcoin uri label escaped expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?label=%26%3D%0A");
    REQUIRE(uri);
    REQUIRE(uri->label() == "&=\n");
}

TEST_CASE("bitcoin uri message escaped expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?message=hello%20bitcoin");
    REQUIRE(uri);
    REQUIRE(uri->message() == "hello bitcoin");
}

TEST_CASE("bitcoin uri r escaped expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?r=http://example.com?purchase%3Dshoes%26user%3Dbob");
    REQUIRE(uri);
    REQUIRE(uri->r() == "http://example.com?purchase=shoes&user=bob");
}

TEST_CASE("bitcoin uri payment valid expected", "[bitcoin uri]") {
    auto const expected_payment = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD";
    auto const expected_uri = std::string("bitcoin:") + expected_payment;
    auto const uri = bitcoin_uri::parse_from(expected_uri);
    REQUIRE(uri);
    REQUIRE(uri->payment().encoded_legacy() == expected_payment);
}

TEST_CASE("bitcoin uri stealth valid expected", "[bitcoin uri]") {
    auto const expected_stealth = "hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i";
    auto const expected_uri = std::string("bitcoin:") + expected_stealth;
    auto const uri = bitcoin_uri::parse_from(expected_uri);
    REQUIRE(uri);
    REQUIRE(uri->stealth().encoded() == expected_stealth);
}

TEST_CASE("bitcoin uri address payment expected", "[bitcoin uri]") {
    auto const expected_payment = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD";
    auto const expected_uri = std::string("bitcoin:") + expected_payment;
    auto const uri = bitcoin_uri::parse_from(expected_uri);
    REQUIRE(uri);
    REQUIRE(uri->address() == expected_payment);
}

TEST_CASE("bitcoin uri address stealth expected", "[bitcoin uri]") {
    auto const expected_stealth = "hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i";
    auto const expected_uri = std::string("bitcoin:") + expected_stealth;
    auto const uri = bitcoin_uri::parse_from(expected_uri);
    REQUIRE(uri);
    REQUIRE(uri->address() == expected_stealth);
}

TEST_CASE("bitcoin uri parameter amount denormalized normalized", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?amount=.0012");
    REQUIRE(uri);
    REQUIRE(uri->parameter("amount") == "0.0012");
}

TEST_CASE("bitcoin uri parameters all complex uri expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from(
        "bitcoin:113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD?"
        "amount=0.0012&"
        "label=%26%3D%0A&"
        "message=hello%20bitcoin&"
        "r=http://example.com?purchase%3Dshoes%26user%3Dbob");
    REQUIRE(uri);

    REQUIRE(uri->address() == "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD");
    REQUIRE(uri->parameter("amount") == "0.0012");
    REQUIRE(uri->parameter("label") == "&=\n");
    REQUIRE(uri->parameter("message") == "hello bitcoin");
    REQUIRE(uri->parameter("r") == "http://example.com?purchase=shoes&user=bob");
}

// Equality / ordering
// ----------------------------------------------------------------------------

TEST_CASE("bitcoin uri equality same value equal", "[bitcoin uri]") {
    auto const a = bitcoin_uri::parse_from("bitcoin:?amount=0.001");
    auto const b = bitcoin_uri::parse_from("bitcoin:?amount=0.001");
    REQUIRE(a);
    REQUIRE(b);
    REQUIRE(*a == *b);
    REQUIRE( ! (*a != *b));
}

TEST_CASE("bitcoin uri inequality different amount not equal", "[bitcoin uri]") {
    auto const a = bitcoin_uri::parse_from("bitcoin:?amount=0.001");
    auto const b = bitcoin_uri::parse_from("bitcoin:?amount=0.002");
    REQUIRE(a);
    REQUIRE(b);
    REQUIRE(*a != *b);
    REQUIRE( ! (*a == *b));
}

// End Test Suite
