// Copyright (c) 2016-present Knuth Project developers.
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <concepts>
#include <string>

#include <test_helpers.hpp>

using namespace kth;
using namespace kd;
using namespace kth::domain::wallet;

// Start Test Suite: bitcoin uri tests

// operator!= is auto-generated by C++20 rewriting `a != b` to `!(a == b)`
// when only `operator==` is defined. Verified at compile time here so
// the invariant surfaces in the closest possible location to the type
// (and mirrors the C-API `_not_equal` binding synthesized by the
// generator).
static_assert(
    requires(bitcoin_uri const& a, bitcoin_uri const& b) {
        { a != b } -> std::same_as<bool>;
        { a == b } -> std::same_as<bool>;
    });

// parse_from
// ----------------------------------------------------------------------------

TEST_CASE("bitcoin uri parse from bitcoin scheme valid", "[bitcoin uri]") {
    REQUIRE(bitcoin_uri::parse_from("bitcoin:", true));
}

TEST_CASE("bitcoin uri parse from scheme mixed case normalized", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcOin:", true);
    REQUIRE(uri);
    REQUIRE(uri->to_string() == "bitcoin:");
}

TEST_CASE("bitcoin uri parse from invalid scheme error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("fedcoin:", true));
}

TEST_CASE("bitcoin uri parse from payment address only error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD", true));
}

TEST_CASE("bitcoin uri parse from stealth address only error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i", true));
}

TEST_CASE("bitcoin uri parse from fragment error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("bitcoin:#satoshi", true));
}

TEST_CASE("bitcoin uri parse from strict reject non ascii", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::parse_from("bitcoin:?label=Some テスト", true));
}

TEST_CASE("bitcoin uri parse from non strict accept non ascii", "[bitcoin uri]") {
    REQUIRE(bitcoin_uri::parse_from("bitcoin:?label=Some テスト", false));
}

// from_parts
// ----------------------------------------------------------------------------

TEST_CASE("bitcoin uri from parts empty is bitcoin scheme only", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::from_parts({});
    REQUIRE(uri);
    REQUIRE(uri->to_string() == "bitcoin:");
}

TEST_CASE("bitcoin uri from parts payment address expected encoding", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::from_parts({.address = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD"});
    REQUIRE(uri);
    REQUIRE(uri->to_string() == "bitcoin:113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD");
}

TEST_CASE("bitcoin uri from parts stealth address expected encoding", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::from_parts({.address = "hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i"});
    REQUIRE(uri);
    REQUIRE(uri->to_string() == "bitcoin:hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i");
}

TEST_CASE("bitcoin uri from parts invalid address error", "[bitcoin uri]") {
    REQUIRE( ! bitcoin_uri::from_parts({.address = "not-a-real-address"}));
}

TEST_CASE("bitcoin uri from parts amount encoded", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::from_parts({.amount = 120000});
    REQUIRE(uri);
    REQUIRE(uri->to_string() == "bitcoin:?amount=0.0012");
}

TEST_CASE("bitcoin uri from parts all fields expected encoding", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::from_parts({
        .address = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD",
        .amount = 120000,
        .label = std::string("&=\n"),
        .message = std::string("hello bitcoin"),
        .r = std::string("http://example.com?purchase=shoes&user=bob"),
    });
    REQUIRE(uri);
    REQUIRE(uri->to_string() ==
                "bitcoin:113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD?"
                "amount=0.0012&"
                "label=%26%3D%0A&"
                "message=hello%20bitcoin&"
                "r=http://example.com?purchase%3Dshoes%26user%3Dbob");
}

// Getters
// ----------------------------------------------------------------------------

TEST_CASE("bitcoin uri amount set expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?amount=0.0012", true);
    REQUIRE(uri);
    REQUIRE(uri->amount() == 120000u);
}

TEST_CASE("bitcoin uri label escaped expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?label=%26%3D%0A", true);
    REQUIRE(uri);
    REQUIRE(uri->label() == "&=\n");
}

TEST_CASE("bitcoin uri message escaped expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?message=hello%20bitcoin", true);
    REQUIRE(uri);
    REQUIRE(uri->message() == "hello bitcoin");
}

TEST_CASE("bitcoin uri r escaped expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?r=http://example.com?purchase%3Dshoes%26user%3Dbob", true);
    REQUIRE(uri);
    REQUIRE(uri->r() == "http://example.com?purchase=shoes&user=bob");
}

TEST_CASE("bitcoin uri payment valid expected", "[bitcoin uri]") {
    auto const expected_payment = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD";
    auto const expected_uri = std::string("bitcoin:") + expected_payment;
    auto const uri = bitcoin_uri::parse_from(expected_uri, true);
    REQUIRE(uri);
    REQUIRE(uri->payment()->encoded_legacy() == expected_payment);
}

TEST_CASE("bitcoin uri stealth valid expected", "[bitcoin uri]") {
    auto const expected_stealth = "hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i";
    auto const expected_uri = std::string("bitcoin:") + expected_stealth;
    auto const uri = bitcoin_uri::parse_from(expected_uri, true);
    REQUIRE(uri);
    REQUIRE(uri->stealth()->to_string() == expected_stealth);
}

TEST_CASE("bitcoin uri address payment expected", "[bitcoin uri]") {
    auto const expected_payment = "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD";
    auto const expected_uri = std::string("bitcoin:") + expected_payment;
    auto const uri = bitcoin_uri::parse_from(expected_uri, true);
    REQUIRE(uri);
    REQUIRE(uri->address() == expected_payment);
}

TEST_CASE("bitcoin uri address stealth expected", "[bitcoin uri]") {
    auto const expected_stealth = "hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i";
    auto const expected_uri = std::string("bitcoin:") + expected_stealth;
    auto const uri = bitcoin_uri::parse_from(expected_uri, true);
    REQUIRE(uri);
    REQUIRE(uri->address() == expected_stealth);
}

TEST_CASE("bitcoin uri parameter amount denormalized normalized", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from("bitcoin:?amount=.0012", true);
    REQUIRE(uri);
    REQUIRE(uri->parameter("amount") == "0.0012");
}

TEST_CASE("bitcoin uri parameters all complex uri expected", "[bitcoin uri]") {
    auto const uri = bitcoin_uri::parse_from(
        "bitcoin:113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD?"
        "amount=0.0012&"
        "label=%26%3D%0A&"
        "message=hello%20bitcoin&"
        "r=http://example.com?purchase%3Dshoes%26user%3Dbob", true);
    REQUIRE(uri);

    REQUIRE(uri->address() == "113Pfw4sFqN1T5kXUnKbqZHMJHN9oyjtgD");
    REQUIRE(uri->parameter("amount") == "0.0012");
    REQUIRE(uri->parameter("label") == "&=\n");
    REQUIRE(uri->parameter("message") == "hello bitcoin");
    REQUIRE(uri->parameter("r") == "http://example.com?purchase=shoes&user=bob");
}

// Equality / ordering
// ----------------------------------------------------------------------------

TEST_CASE("bitcoin uri equality same value equal", "[bitcoin uri]") {
    auto const a = bitcoin_uri::parse_from("bitcoin:?amount=0.001", true);
    auto const b = bitcoin_uri::parse_from("bitcoin:?amount=0.001", true);
    REQUIRE(a);
    REQUIRE(b);
    REQUIRE(*a == *b);
    REQUIRE( ! (*a != *b));
}

TEST_CASE("bitcoin uri inequality different amount not equal", "[bitcoin uri]") {
    auto const a = bitcoin_uri::parse_from("bitcoin:?amount=0.001", true);
    auto const b = bitcoin_uri::parse_from("bitcoin:?amount=0.002", true);
    REQUIRE(a);
    REQUIRE(b);
    REQUIRE(*a != *b);
    REQUIRE( ! (*a == *b));
}

// End Test Suite
