name: Docker image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: kth version to build (e.g. v1.0.0)
        required: true
        type: string

jobs:
  node-image:
    permissions:
      contents: read
      packages: write
    uses: k-nuth/docker-images/.github/workflows/build-node.yml@master
    with:
      version: ${{ github.event.release.tag_name || inputs.version }}
